function [ cFKparams ] = getcFKsimParams( logfile )

[~,hStr]=system(['awk "/ h:/ {print \$2; exit}" <' logfile]);
cFKparams.h=str2num(hStr);
[~,kStr]=system(['awk "/ k:/ {print \$2; exit}" <' logfile]);
cFKparams.k=str2num(kStr);
[~,TempStr]=system(['awk "/ Temp eq:/ {print \$3; exit}" <' logfile]);
cFKparams.Temp=str2num(TempStr);
[~,Nstr]=system(['awk "/ particles N:/ {print \$3; exit}" <' logfile]);
cFKparams.N=str2num(Nstr);
[~,Lstr]=system(['awk "/ System length units:/ {print \$4; exit}" <' logfile]);
cFKparams.L=str2num(Lstr);
[~,aStr]=system(['awk "/ ax:/ {print \$2; exit}" <' logfile]);
cFKparams.a=str2num(aStr);
[~,WLstr]=system(['awk "/ WL:/ {print \$2; exit}" <' logfile]);
cFKparams.WL=str2num(WLstr);
%[~,eqTstr]=system(['awk "/ eq steps:/ {printf \"%f\", \$3; exit}" <' logfile]);
[~,eqTstr]=system(['awk "/ eq steps:/ {print \$3; exit}" <' logfile]);
cFKparams.eqtime=str2num(eqTstr);
[~,timeSteps]=system(['awk "/ Total steps:/ {print \$3; exit}" <' logfile]);
cFKparams.timeSteps=str2num(timeSteps);
[~,totalTime]=system(['awk "/ Total time \(s\):/ {print \$4; exit}" <' logfile]);
cFKparams.totalTime=str2num(totalTime);
[~,ens]=system(['awk "/ ens:/ {print \$2; exit}" <' logfile]);
cFKparams.ens=int16(str2num(ens));
cFKparams.ensStr=['run ' num2str(cFKparams.ens)];
