function [ nonFluidGeometry ] = getNonFluidGeometry( pdb, geometryFile );
% Returnthe locations of the nanotube ends, and the graphene sheets

[ stat, outp ] = system(sprintf('vmd -dispdev text -pdb %s -e ../vmd/outputNonFluidGeometry.tcl -args %s',pdb,geometryFile));
geometryData = dlmread(geometryFile)
systemMiddle = mean(geometryData(:));
nonFluidGeometry = struct(  
                            'cntBtm', geometryData(1,1), ...
                            'cntTop', geometryData(1,2), ...
                            'membraneBtm', geometryData(2,1), ...
                            'membraneTop', geometryData(2,2), ...
                            'pistonBtm', geometryData(3,1), ...
                            'pistonTop', geometryData(3,2), ...
                            'systemMiddle', systemMiddle ...
                            );
