availableModules = {'fft', ...
                    'trackReservoirs', ...
                    'makeMovie', ...
                    'countSolitons', ...
                    'measureMotion', ...
                    'plotOverview' ...
};
